# Generated by Django 3.2.9 on 2021-12-08 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('87cd7b3d-d377-4e17-98ac-747cea3faefd'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
