# Generated by Django 3.2.9 on 2021-12-08 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f174c4f3-6cf6-4567-9888-f3fb755c09fe'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
