# Generated by Django 3.2.9 on 2021-12-08 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_auto_20211208_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b31668a2-b19f-4918-974a-5d8c9cacfcfd'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
