# Generated by Django 3.2.9 on 2021-12-08 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0005_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2322b89f-b4f5-4c13-9a60-7b45524ab971'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
