# Generated by Django 3.2.9 on 2021-12-09 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0008_auto_20211209_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db43dacd-0205-4259-97f0-3c8cee8e43b8'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
